apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range tuple  "server.properties" "server.properties.template" "zookeeper.properties" "tools-log4j.properties" "producer.properties" "log4j.properties" "consumer.properties" }}
  {{ . }}: |-
{{ $files.Get . | indent 4 }}
  {{- end }}
