name: archbox-zookeeper
replicas: 3
# minAvailable: 2
resources:
  requests:
    cpu: 100m
    memory: 256Mi 
  limits:
    cpu: 200m
    memory: 500Mi
storage: "1Gi"
storageClassName: default 
serverPort: 2888
leaderElectionPort: 3888
clientPort: 2181
imagePullPolicy: "Always"
tickTimeMs: 2000
initTicks: 10
syncTicks: 10
clientCnxns: 60
snapRetain: 3
purgeHours: 0
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
logLevel: "INFO"
security:
  enabled: false
  runAsUser: 1000
  fsGroup: 1000
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "zookeeper"
        topologyKey: "kubernetes.io/hostname"
