{{- if .Release.IsInstall -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "zookeeper.name" . }}
  labels:
    app: {{ include "zookeeper.name" . | quote }}
    chart: {{ include "zookeeper.chartWithVersion" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ include "zookeeper.name" . | quote }}
      release: {{ .Release.Name | quote }}
  {{- if .Values.minAvailable }}
  minAvailable: {{ .Values.minAvailable }}
  {{- else }}
  minAvailable: {{ sub .Values.replicas 1 }}
  {{- end }}
{{- end -}}
