apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.name" . }}-headless
  labels:
    app: {{ include "zookeeper.name" . | quote }}
    chart: {{ include "zookeeper.chartWithVersion" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - port: {{ .Values.serverPort }}
    name: server
  - port: {{ .Values.leaderElectionPort }}
    name: leader-election
  clusterIP: None
  selector:
    app: {{ include "zookeeper.name" . | quote }}
    release: {{ .Release.Name | quote }}
